import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import ReduxProvider from "@/components/providers/redux-provider";
import ReactQueryProvider from "@/components/providers/react-query-provider";

import "./globals.css";

const firaSans = Fira_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Fuse8 | Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <ReduxProvider>
        <html lang="en">
          <body className={firaSans.className}>{children}</body>
        </html>
      </ReduxProvider>
    </ReactQueryProvider>
  );
}
